name: Upload to S3 test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Upload html files to S3 bucket
        run: |
          aws s3 cp . s3://test.ushomi-musambani.de/ --exclude "*" --include "*.html" --exclude "*/*"
          aws s3 cp ./favicon.ico s3://test.ushomi-musambani.de/
          aws s3 cp ./robots.txt s3://test.ushomi-musambani.de/
          aws s3 cp ./resources s3://test.ushomi-musambani.de/ --recursive
